name: cats_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  get_it: ^9.2.0
  dio: ^5.9.0
  flutter_native_splash: ^2.3.1

flutter_native_splash:
  color: "#ffffff"         
  image: assets/images/logo.png  
  image_android: assets/images/logo.png
  image_ios: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#ffffff"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  bloc_test: ^9.1.7 
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

assets:
    - assets/images/logo.png

